In [1]:
# ============================================================
# 라이브러리 Import
# ============================================================

# 데이터 처리 및 분석
import os
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import warnings

# 시각화
import matplotlib.pyplot as plt
import seaborn as sns

# 통계 분석
from scipy import stats
from scipy.stats import shapiro, levene, ttest_ind, chi2_contingency, f_oneway
from scipy.stats import mannwhitneyu, fisher_exact, kruskal
from scipy.stats import skew, kurtosis
from statsmodels.stats.multicomp import pairwise_tukeyhsd, MultiComparison
import pingouin as pg
import scikit_posthocs as sp

# 머신러닝
from sklearn.preprocessing import MinMaxScaler

# 출력 설정
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# 한글 폰트 설정
import platform
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':  # macOS
    plt.rcParams['font.family'] = 'AppleGothic'
else:  # Linux
    plt.rcParams['font.family'] = 'NanumGothic'

plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.figsize'] = (12, 6)

# 참고: seed 고정으로 팀원 간 동일한 결과 재현 가능
np.random.seed(42)

print("="*60)
print("라이브러리 로드 완료!")
print("한글 폰트 설정 완료!")
print("="*60)

#모든 컬럼 다 보이게
pd.set_option("display.max_columns", None)
#모든 행도 다 보이게
pd.set_option("display.max_rows", None)


#판다스가 화면에 보여줄 때 잘리지 않게 출력 옵션을 바꾸기
#pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 200)

============================================================
라이브러리 로드 완료!
한글 폰트 설정 완료!
============================================================

In [2]:
full_data = pd.read_csv("full_data.csv") #전처리 파일 저장하면 이걸로 시작

In [3]:
# 1. 파일 위치
metadata_file = "./metadata.csv"
data_folder = "./data"

# 2. metadata 불러오기
df = pd.read_csv(metadata_file)

# 3. 컬럼명 공백 제거
df.columns = df.columns.str.strip()

In [18]:
full_data.head()

,Voltage_measured,Current_measured,Temperature_measured,Current_load,Voltage_load,Time,filename,type,battery_id,start_time,Sense_current,Battery_current,Current_ratio,Battery_impedance,Rectified_Impedance,Current_charge,Voltage_charge
0,4.246711,0.000252,6.212696,0.0002,0.000,0.000,00001.csv,discharge,B0047,[2010. 7. 21. 15. 0. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4.246764,-0.001411,6.234019,0.0002,4.262,9.360,00001.csv,discharge,B0047,[2010. 7. 21. 15. 0. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.039277,-0.995093,6.250255,1.0000,3.465,23.281,00001.csv,discharge,B0047,[2010. 7. 21. 15. 0. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.019506,-0.996731,6.302176,1.0000,3.451,36.406,00001.csv,discharge,B0047,[2010. 7. 21. 15. 0. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.004763,-0.992845,6.361645,1.0000,3.438,49.625,00001.csv,discharge,B0047,[2010. 7. 21. 15. 0. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
type_count = full_data["type"].value_counts(dropna=False)
print("\n[타입별 개수]")
print(type_count)

[타입별 개수]
type
charge       6512876
discharge     770070
impedance      93888
Name: count, dtype: int64

In [24]:
battery_count = full_data["battery_id"].value_counts(dropna=False)
print("\n[battery_id별 행 개수 상위 20개]")
print(battery_count.head(20))

print("\n[battery_id 개수]")
print(full_data["battery_id"].nunique())

[battery_id별 행 개수 상위 20개]
battery_id
B0006    604802
B0005    604802
B0007    604802
B0034    411228
B0033    411228
B0036    411228
B0018    317220
B0043    279536
B0042    279536
B0044    279536
B0054    261592
B0056    261589
B0055    261589
B0039    139767
B0040    139767
B0038    139767
B0041    139686
B0047    127404
B0045    127404
B0048    127404
Name: count, dtype: int64

[battery_id 개수]
34

In [25]:
type_battery_count = full_data.groupby("type")["battery_id"].nunique()
print("\n[타입별 battery_id 개수]")
print(type_battery_count)

[타입별 battery_id 개수]
type
charge       34
discharge    34
impedance    34
Name: battery_id, dtype: int64

In [ ]:
fill_ratio = full_data.notnull().groupby(full_data["type"]).mean() * 100
print("타입별 notnull 비율(%)")
print(fill_ratio.T)

타입별 컬럼 채워진 비율(%)
type                      charge  discharge  impedance
Voltage_measured       99.996054      100.0       0.00
Current_measured       99.996054      100.0       0.00
Temperature_measured   99.996054      100.0       0.00
Current_load            0.000000      100.0       0.00
Voltage_load            0.000000      100.0       0.00
Time                  100.000000      100.0       0.00
filename              100.000000      100.0     100.00
type                  100.000000      100.0     100.00
battery_id            100.000000      100.0     100.00
start_time            100.000000      100.0     100.00
Sense_current           0.000000        0.0     100.00
Battery_current         0.000000        0.0     100.00
Current_ratio           0.000000        0.0     100.00
Battery_impedance       0.000000        0.0     100.00
Rectified_Impedance     0.000000        0.0      81.25
Current_charge        100.000000        0.0       0.00
Voltage_charge        100.000000        0.0       0.00

In [4]:
def clear_time(x):
    # 사용할 리스트
    nums = []

    # 임시 저장용
    current = ''

    # 반복문으로 숫자만 뽑아내기
    for ch in x:
        # 숫자형이거나 형태 다른 숫자 뽑아내기
        if ch.isdigit() or ch in ['.', '_', 'e', 'E', '+']:
            current += ch
        else:
            if current != '':
                nums.append(current)
                current = ''

    # 숫자 남아있을 수도 있으니 한번 더 리스트에 append
    if current != '':
        nums.append(current)

    # 연월일시분초 하면 최소 6자리, 그 이하는 버림
    if len(nums) < 6:
        return None

    # num 리스트 숫자형으로 변환, 연월일시분초이므로 앞에 6개만 숫자 변환
    try:
        nums = list(map(float, nums[:6]))
    except:
        return None

    # 각 숫자에 의미 부여
    year, month, day, hour, minute, second = nums

    # 이상치 제거
    if not (
        2000 < year
        and 1 <= month <= 12
        and 1 <= day <= 31
        and 0 <= hour < 24
        and 0 <= minute < 60
        and 0 <= second < 60
    ):
        return None

    # Timestamp로 date_time 변환
    return pd.Timestamp(
        int(year), int(month), int(day),
        int(hour), int(minute), int(second)
    )


df['start_time'] = df['start_time'].apply(clear_time)
df = df.dropna(subset=['start_time'])

In [5]:
df.nunique()

type                      3
start_time             2443
ambient_temperature       5
battery_id               34
test_id                 615
uid                    7412
filename               7412
Capacity               2703
Re                     1910
Rct                    1910
dtype: int64

In [ ]:
#for i in range(1, 10):
    #df1 = pd.read_csv(f'data/data1/0000{i}.csv')
    #print(i, df1.columns)

1 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_load', 'Voltage_load', 'Time'], dtype='str')
2 Index(['Sense_current', 'Battery_current', 'Current_ratio', 'Battery_impedance', 'Rectified_Impedance'], dtype='str')
3 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_charge', 'Voltage_charge', 'Time'], dtype='str')
4 Index(['Sense_current', 'Battery_current', 'Current_ratio', 'Battery_impedance', 'Rectified_Impedance'], dtype='str')
5 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_load', 'Voltage_load', 'Time'], dtype='str')
6 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_charge', 'Voltage_charge', 'Time'], dtype='str')
7 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_load', 'Voltage_load', 'Time'], dtype='str')
8 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_charge', 'Voltage_charge', 'Time'], dtype='str')
9 Index(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_load', 'Voltage_load', 'Time'], dtype='str')

1번 5번 세트 /3번 'Voltage_charge' / 2번 4번 세트

- 00001.csv → Discharge(방전) = 첫 번째 방전 기록
- 00002.csv → Impedance(임피던스) = 그 사이 상태 진단
- 00003.csv → Charge(충전) = 다음 충전 기록
- 00004.csv → Impedance(임피던스) = 또 상태 진단
- 00005.csv → Discharge(방전) = 다음 방전 기록

데이터는 한 줄 한 줄이 “일반 거래 데이터”가 아니라, 배터리의 충전/방전/임피던스 측정 사이클을 의미합니다.
=> 리튬이온 배터리를 여러 번 충전·방전·임피던스 측정한 실험 기록

Charge → Discharge = 1 cycle

- type	실험 유형 (charge, discharge, impedance)
- start_time	테스트 시작 시간
- ambient_temperature	실험 환경의 온도(°C)
- battery_id	배터리 식별 ID
- test_id	실험 ID
- uid	실험 샘플 ID
- filename	데이터 파일명
- Capacity	배터리 현재 용량(Ah)
- Re	전해질 저항(Ω)
- Rct	충전 전달 저항(Ω)
- Voltage_measured	배터리 측정 전압(V)
- Current_measured	배터리 측정 전류(A)
- Temperature_measured	배터리 실시간 온도(°C)
- Current_load	배터리 부하 전류(A)
- Voltage_load	배터리 부하 전압(V)

In [6]:
df['battery_id'].nunique()

34

In [7]:
df['battery_id'].value_counts()

battery_id
B0006    607
B0005    607
B0007    607
B0034    477
B0033    477
B0036    477
B0018    312
B0043    268
B0042    268
B0044    268
B0054    246
B0056    245
B0055    245
B0047    182
B0045    182
B0048    182
B0046    182
B0041    160
B0053    133
B0039    117
B0040    117
B0038    117
B0032     96
B0029     96
B0030     96
B0031     96
B0028     77
B0027     77
B0025     77
B0026     77
B0049     61
B0050     61
B0052     61
B0051     61
Name: count, dtype: int64

In [8]:
summary = pd.DataFrame({
    "dtype": df.dtypes,
    "non_null": df.count(),
    "null": df.isnull().sum()
})

summary

                              dtype  non_null  null
type                            str      7412     0
start_time           datetime64[us]      7412     0
ambient_temperature           int64      7412     0
battery_id                      str      7412     0
test_id                       int64      7412     0
uid                           int64      7412     0
filename                        str      7412     0
Capacity                        str      2745  4667
Re                              str      1910  5502
Rct                             str      1910  5502

# []처리

In [12]:
df['Capacity'].isnull().sum()

np.int64(4667)

In [9]:
df['Capacity'].value_counts().sort_values(ascending=False)

Capacity
[]                      25
0                       19
1.6743047446975208       1
1.5243662105099023       1
1.5080762969973425       1
1.4835577960067696       1
1.4671391666146525       1
1.448858156982267        1
1.4458534180949325       1
1.431118266178283        1
1.4192745516578533       1
1.3999974221808271       1
1.3885156686114437       1
1.3652234669528964       1
1.4060442272970963       1
1.4057541613525781       1
1.3867662881727878       1
1.3705053061420223       1
1.3497431114823601       1
1.3251533367939783       1
1.3111943869635805       1
1.3394234405932892       1
1.2849157142560723       1
1.281719159327807        1
1.2600051642942829       1
1.266070385993126        1
1.2413590294280803       1
1.2298873703485311       1
1.228088614506696        1
1.2139857189070042       1
1.2173435064564189       1
1.2073445944515917       1
1.18804049227045         1
1.186304749886542        1
1.2613935471028506       1
1.2648246158850653       1
1.2466494548982199       1
1.2333924152795082       1
1.2129250072037692       1
1.1999106597943647       1
1.1902559038393383       1
1.1892563795455853       1
1.167069685125939        1
1.1615348403090369       1
1.1555563844349988       1
1.1488524666097713       1
1.143572986788779        1
1.1418015379428537       1
1.136058647502255        1
1.1236364680969286       1
1.1320498900328944       1
1.1170101762158153       1
1.120043039721982        1
1.1059773445917063       1
1.1907902374762016       1
1.2012387088454022       1
1.1906909549024802       1
1.1764375730308343       1
1.1628110372792353       1
1.1516152840582585       1
1.1583673498348623       1
1.1692285288386206       1
1.1588148476218465       1
1.1439588147705457       1
1.1383941068159398       1
1.2213102850395667       1
1.2031062978889062       1
1.1897147112197684       1
1.177422568842014        1
1.158443027293818        1
1.1567087516841796       1
1.0819793880779518       1
0.927952404748273        1
0.885193608411576        1
0.8581010699478283       1
0.8409352213456689       1
0.8245471942901911       1
0.7935960418803983       1
0.8183676087159205       1
0.7977644276409412       1
0.7993777411831636       1
0.7783107440628891       1
0.7803738231239117       1
0.7713058245640294       1
0.795279016979026        1
0.7824128169919247       1
0.7649414992231182       1
0.7544899426779375       1
0.7504048978314295       1
0.7407258109620256       1
0.7308525593793626       1
0.7287255851177903       1
0.7161023377036263       1
0.7129204834988017       1
0.7141991829499618       1
0.7190570819844222       1
0.7173975428775917       1
0.7071027496463946       1
0.703531206505542        1
0.6941108278958862       1
0.6914114388869608       1
0.6971551798505504       1
0.6832460217432723       1
0.6822029317493292       1
0.7289529213213379       1
0.7139321758287004       1
0.6957731747455482       1
0.7018312962317095       1
0.6911808244378487       1
0.6843279752855028       1
0.6741394908812485       1
0.6670070174301739       1
0.6804085117374855       1
0.6617864063235485       1
0.6623168733492338       1
0.6679358357181778       1
0.6488990885270688       1
0.6503639129625527       1
0.6572077690202801       1
0.6363517458476216       1
0.6536449360948587       1
0.6391428272150887       1
0.6482206049496236       1
0.6287957471922729       1
0.6380571850193401       1
0.6554825047832906       1
0.6484934835397033       1
0.6454071687844921       1
0.6427008031845645       1
0.6352454880802477       1
0.6156760019587869       1
0.6170833682807023       1
0.6434227390858672       1
0.6278124433742752       1
0.6290078315253372       1
0.6266355568292261       1
0.6495813516716594       1
0.6337485177966306       1
0.6298550929085645       1
0.6183063778386736       1
0.6069476168507777       1
1.6579955793677608       1
1.5076933476098775       1
1.4989223343608031       1
1.4782919502497789       1
1.461856891390611        1
1.4509592706473475       1
1.451746997147108        1
1.444392866287476        1
1.432738323965376        1
1.417241201438662        1
1.4057559944573452       1
1.3902706269897063       1
1.4196659307880326       1
1.4190563985232272       1
1.404272356704056        1
1.3916140490958342       1
1.3749618350294734       1
1.3545155713071164       1
1.3440223073315984       1
1.372384475860572        1
1.3184105752674413       1
1.3112727599578604       1
1.2970172419001187       1
1.2995219526631718       1
1.2826154066729571       1
1.2752890152407          1
1.2735572473264072       1
1.2594114333938535       1
1.2631632585495876       1
1.2491717310136363       1
1.233984347835307        1
1.240031992028868        1
1.30370857198071         1
1.315055963470538        1
1.2888738300982074       1
1.2877137595885193       1
1.2673379985315463       1
1.250594345697306        1
1.2487131179395878       1
1.248002326082933        1
1.2300895244599586       1
1.2244197121500935       1
1.2186682845116386       1
1.2037865236033616       1
1.1947642300832226       1
1.2052091893871497       1
1.1955746593628465       1
1.1888497102149884       1
1.1915605250807406       1
1.1726587153109655       1
1.1841133872494156       1
1.1576825122317769       1
1.259355851168598        1
1.265883375278026        1
1.2472598673184119       1
1.232808747256218        1
1.2319592783041904       1
1.220785786262778        1
1.2275441303266783       1
1.2386788414290355       1
1.2283577755407058       1
1.2095481507570451       1
1.2082142070681048       1
1.2998734542832147       1
1.2691220651743778       1
1.2555144634690785       1
1.2519876926897657       1
1.2374982003019996       1
1.2231273969878986       1
1.7282392323598248       1
1.5161488467923143       1
1.503121190703977        1
1.48586566102824         1
1.4694562316392716       1
1.4589554592644807       1
1.4556853555098295       1
1.456232262380321        1
1.4440592236675138       1
1.428294264765868        1
1.4199848948034668       1
1.4043226018516568       1
1.4234351301615986       1
1.4339948857967295       1
1.4185177047756572       1
1.4056313337829422       1
1.3890214025155618       1
1.3723339082737365       1
1.3615778905990565       1
1.4100282016237429       1
1.3395671374926488       1
1.3291515487117478       1
1.3181687033905718       1
1.312423708466101        1
1.2993237532162487       1
1.2877483042174591       1
1.2865282739749122       1
1.2719636386987183       1
1.2714495345417192       1
1.2615423884659074       1
1.2421201619204132       1
1.2402537441669796       1
1.2851130012242886       1
1.3043327841699193       1
1.2778639041619957       1
1.2723464591651539       1
1.2477883952768762       1
1.2352499196655526       1
1.229251291851949        1
1.223890910501634        1
1.205423323571373        1
1.1957824090008151       1
1.1900729496698461       1
1.179201763233652        1
1.169504032514554        1
1.16772376849918         1
1.1579256145829042       1
1.1499812813376982       1
1.150285902223034        1
1.1349452274085248       1
1.1380960963513609       1
1.123711172150547        1
1.214119211354098        1
1.211944797522819        1
1.1971248679331923       1
1.1822892151870987       1
1.1645336676778397       1
1.1535559567518647       1
1.1601987101282065       1
1.1711716308206082       1
1.1563410270783216       1
1.141082456193516        1
1.1352383596118123       1
1.2530847858282803       1
1.2050453590356518       1
1.19119860196273         1
1.17463817374538         1
1.1555432048235512       1
1.1538041170229467       1
1.713782642126885        1
1.6955681658647108       1
1.6814906372051954       1
1.6786372409532953       1
1.6694168550864992       1
1.6506423382064332       1
1.6424273190907783       1
1.6353664801041328       1
1.633232875930849        1
1.6258840554387932       1
1.617976174654771        1
1.6136652707273988       1
1.605821026619692        1
1.6033527961961531       1
1.5951342406182645       1
1.5878135544728507       1
1.5800601969084245       1
1.575565087879128        1
1.5950169012164208       1
1.5898075522577595       1
1.5807953202097411       1
1.5704333289187615       1
1.5643368431897877       1
1.558307017802491        1
1.5537149289772467       1
1.549528250585513        1
1.5424430535161062       1
1.54256227031715         1
1.5309356452520158       1
1.5247733176952427       1
1.5196742408779502       1
1.5123696925788683       1
1.499914486202397        1
1.4924106271188253       1
1.492624987952706        1
1.4924024018806028       1
1.4853020201751674       1
1.477208127101587        1
1.4694738525181406       1
0.057034391042653794     1
0.0571536334895882       1
0.05729366005937665      1
0.05744203185278054      1
0.06713062107721124      1
0.06714781920234739      1
0.06732001211690299      1
0.06784038051613318      1
0.06799604927210635      1
0.06828011147886554      1
0.06844632943125976      1
0.06851361914788083      1
0.06887402435616684      1
0.056544389321695726     1
0.06918353164189846      1
0.059122086455436665     1
0.06956120084140223      1
0.07017897804376615      1
0.07028148183862523      1
0.05787364202878375      1
0.07056618554293374      1
0.057989410208958        1
0.07129266446800787      1
0.07146546557664281      1
0.0716254973792324       1
0.07192596356272017      1
0.058840095111364746     1
0.07213853480103966      1
0.07231835711877917      1
0.05938170626668099      1
0.07294488485625279      1
0.07306917734079586      1
0.07317054128128272      1
0.07347430293304898      1
0.06010697591831878      1
0.07383162509955737      1
0.060495215307428206     1
0.060604010237618126     1
0.06073438432235217      1
0.06099653048237791      1
0.061130459259873135     1
0.06129124410987595      1
0.06130329065804092      1
0.061151661574090986     1
0.061405387192057306     1
0.06175780765942851      1
1.5250840516518187       1
1.552568811301301        1
1.5427752626774387       1
1.5331932831264679       1
1.5152721949172019       1
1.5074989761997712       1
1.4896288908647644       1
1.4780778852088083       1
1.4700035345334466       1
1.4565623180137077       1
1.445976962830235        1
1.4325855992469252       1
1.4197344854662965       1
1.401262575071573        1
1.3862945308535968       1
1.384130256052478        1
1.361508332192898        1
1.351001663879717        1
1.3282588067265129       1
1.3257206687421472       1
1.3142909715978441       1
1.3003260094811093       1
1.2881071401556836       1
1.2767801501201566       1
1.7048641073512139       1
1.8940319526948572       1
1.8747686491853095       1
1.8654947184112376       1
1.8527398169018068       1
1.844174397003866        1
1.8430238477512753       1
1.8302818174911863       1
1.8173838456081814       1
1.8057992981104682       1
1.8149829605049186       1
1.7995150369321797       1
1.7866516942518147       1
1.7735550719416031       1
1.769995333364443        1
1.799526080374287        1
1.7968530684449833       1
1.7838265504081745       1
1.7696444491040102       1
1.7512940457049684       1
1.7697554297961993       1
1.7547726933914918       1
1.7389166355812984       1
1.7337200518764075       1
1.7150972597500092       1
1.7462926148815636       1
1.719149261914565        1
1.711582246191498        1
1.7005124371100973       1
1.7080989351250158       1
1.691435430587127        1
1.6844494328889932       1
1.664037581688075        1
1.6686372014231974       1
1.6899344075625968       1
1.669431712846442        1
1.6634226761839213       1
1.6436152195947373       1
1.6358000873538245       1
0.11903831859341765      1
0.4729861500927512       1
0.16280793829202067      1
0.4787632853388766       1
0.4711383364607152       1
0.4668172561120673       1
0.4627052684317185       1
0.4412227248835694       1
0.44354421943965844      1
0.4126655541164234       1
1.7461791006389626       1
1.7695250734505363       1
1.7715391419501945       1
1.770625483958279        1
1.7704040639447296       1
1.7695081788801759       1
1.7638356274269416       1
1.7715725869786123       1
1.7701196454489683       1
1.7667569752860521       1
1.7648743629092642       1
1.763838685943225        1
1.7657225752056789       1
1.7645632809383045       1
1.7608991948479125       1
1.7598362095817717       1
1.7590955400143164       1
1.7560495443976523       1
1.7571677199949287       1
1.7558911269459976       1
1.7533419072229914       1
1.7506673845335168       1
1.7510006664162403       1
1.7496058853847873       1
1.7477359172183355       1
1.7444225468099093       1
1.743308366083936        1
1.6556691733888471       1
1.64297669457593         1
1.6343822729361266       1
1.6265067062165601       1
1.618865991735961        1
1.6114968339209264       1
1.3240805773461226       1
1.3153386221697692       1
0.6734628137095633       1
0.7913062105760345       1
0.7865824034601745       1
0.7795871426061582       1
0.7628241523125163       1
0.7405021514606399       1
0.7733165409025605       1
0.7407399462256391       1
0.7446218752617147       1
0.7149875629820736       1
1.7075144448533202       1
1.730880859428193        1
1.7328212845233328       1
1.7317734323431513       1
1.7341296392350067       1
1.7334756929990074       1
1.7243057179457875       1
1.7318975861687205       1
1.7333691208377457       1
1.732175650153278        1
1.7334832776102866       1
1.732372495746513        1
1.7338175297202416       1
1.7329630786357868       1
1.7318839084573339       1
1.7306960059812662       1
1.7296011601947467       1
1.7296187381064656       1
1.7307198617163877       1
1.729274556175907        1
1.7297962212599596       1
1.7268942069037494       1
1.7272191689306016       1
1.7285674981160106       1
1.726636381605547        1
1.7262424141835067       1
1.7252725927602899       1
1.6668026877455053       1
1.666754853762041        1
1.6583274448761054       1
1.65032263550715         1
1.6493406341242296       1
1.641919055037739        1
0.425812451177779        1
0.5569902643736575       1
1.697507332205763        1
1.844701206961174        1
1.8254376674722927       1
1.815750429913437        1
1.8132993337127028       1
1.8151647619660576       1
1.8143317955190057       1
1.801343601809866        1
1.7881558802945825       1
1.7760714604539518       1
1.7852807447597443       1
1.7698116401111978       1
1.7565231680521758       1
1.7543413277348154       1
1.7392875506998715       1
1.7797845109331345       1
1.7657088508465202       1
1.7523941408724169       1
1.7380191225603105       1
1.7312214443143976       1
1.7379128985265808       1
1.7224270683625882       1
1.7184213765608034       1
1.7010220930648232       1
1.693698739563104        1
1.713072721286705        1
1.6976972688567131       1
1.6899314034061208       1
1.678389965463405        1
1.6737947494868326       1
1.6687898927884715       1
1.6492566306631427       1
1.6409676757039668       1
1.6456360229757092       1
1.654547743574037        1
1.6461201520877546       1
1.6275119188151763       1
1.6200530533464497       1
1.612079811711934        1
1.8046847720100736       1
1.8047833214525881       1
1.797618668222458        1
1.7929913687761174       1
1.7919180081592216       1
1.775026135903797        1
1.7920487852223415       1
1.790475801581265        1
1.7868365091987264       1
1.7871529619962185       1
1.7816340617009505       1
1.7850235136604733       1
1.7789060856417256       1
1.7738387518973049       1
1.769682881523146        1
1.7408787283206992       1
1.7648189744011906       1
1.7617857390844023       1
1.75770610357021         1
1.7519375960601256       1
1.7521244035832177       1
1.7597714133989641       1
1.7483011320324189       1
1.7411482627836237       1
1.7363833316311177       1
1.736559066269527        1
1.7172335652295245       1
1.7287126633755356       1
1.7314706281853145       1
1.7282350363146088       1
1.720344742291621        1
1.7221734367707637       1
1.7036476485918646       1
1.6958375743577971       1
1.6949064846676911       1
1.6874768094352455       1
1.685989172917945        1
1.6782864747774933       1
1.6739647640901527       1
1.6722378801237066       1
1.6759897900491967       1
1.6618247672847988       1
1.6606710352566112       1
1.6530644874507203       1
1.649953986270456        1
1.681297805444492        1
1.6700520424481298       1
1.667181860354792        1
1.6568865613275168       1
1.6449819446579936       1
1.639214585000014        1
1.6410599890208055       1
1.6432696512198481       1
1.6298673102402295       1
1.6238536344658807       1
1.6186308887044174       1
1.6193418112441196       1
1.614593271326993        1
1.6072040891927848       1
1.6012663590062357       1
1.5940407410631041       1
1.5946888289374477       1
1.5882100957302596       1
1.587985558077698        1
1.5799165406650344       1
1.5655946193652834       1
0.07070127737340176      1
0.08416878530139071      1
0.08443785621465827      1
0.08478919060590338      1
0.09334258183442584      1
0.10603180131397782      1
0.106505866207118        1
0.09439111585512952      1
0.09450595927387112      1
0.08211456108215626      1
0.09518470631946747      1
0.09539129998659052      1
0.08289664565854568      1
0.08343199036452603      1
0.09624772156495698      1
0.0871279249656989       1
0.09681912182757578      1
0.08440054891345107      1
0.09770121716674529      1
0.08517426476572666      1
0.08471993544879124      1
0.08548836969893649      1
0.08577749933433501      1
0.08595553255245832      1
0.08614796979658328      1
0.08652450808993331      1
0.08676036428685732      1
0.08662025389371077      1
0.0869802394927499       1
0.07387787113473963      1
0.08775865702231889      1
0.08790576300272998      1
0.08808784882200178      1
0.08834250268158712      1
0.07463055332745072      1
0.07485698665122698      1
0.07527573643141765      1
0.07532351860488727      1
0.07553765302367196      1
0.07584285606128259      1
0.0759921803489148       1
0.07621652609591999      1
0.06216923141552526      1
0.0759822277461493       1
0.06227013548943564      1
0.06259446608798445      1
1.4377344766079456       1
1.5246019289244055       1
1.5215273965539478       1
1.5155323631175952       1
1.5044249661534554       1
1.5001507149498807       1
1.489011227320312        1
1.4810149357562845       1
1.476262027748574        1
1.4662551025438961       1
1.4593282593817019       1
1.445704157754381        1
1.4400686089389023       1
1.4290313659547842       1
1.414172188151386        1
1.415603079129078        1
1.3959635285794907       1
1.3929784652630588       1
1.3740772023800918       1
1.3752493030002435       1
1.3671966130854505       1
1.356887600783644        1
1.3449320225969348       1
1.3374691704584258       1
0.7459302957645664       1
1.6623217152845853       1
1.645087369694532        1
1.620729289277574        1
1.5967402025126005       1
1.4856500618812698       1
1.4866702197497013       1
1.4701330958405268       1
1.4565041801019636       1
1.4418961035576472       1
1.4370949588970292       1
1.4458703624967404       1
1.4321040545618373       1
1.426720633302465        1
1.4230846885129826       1
1.4409479522418907       1
1.486901544051865        1
1.5245313226850703       1
1.4629049605190707       1
1.4230794508549893       1
1.4051040863603435       1
1.6329463925070862       1
1.5687138208259117       1
1.5149520966053402       1
1.4855182940634626       1
1.480771929049074        1
1.484026357317059        1
1.4922153055506522       1
1.473312924099279        1
1.441593178980006        1
1.4225873198015788       1
1.4266489379486664       1
1.4596775560238577       1
1.4396159938545154       1
1.4195512657848512       1
1.4118101714470452       1
1.4044196701845313       1
1.4735059098606866       1
1.492658600645149        1
1.4820260149945934       1
1.423575357658995        1
1.4038252197245347       1
1.5363173478836125       1
1.5440367168176732       1
1.507892155360249        1
1.8203060058691092       1
1.5936575758226643       1
1.533070464968097        1

In [10]:
df["Capacity"].apply(type).value_counts()

Capacity
<class 'float'>    4667
<class 'str'>      2745
Name: count, dtype: int64

In [9]:
df.loc[df["Capacity"].map(type) == str, "Capacity"]

0         1.6743047446975208
4         1.5243662105099023
6         1.5080762969973425
8         1.4835577960067696
10        1.4671391666146525
12         1.448858156982267
16        1.4458534180949325
20         1.431118266178283
22        1.4192745516578533
24        1.3999974221808271
26        1.3885156686114437
28        1.3652234669528964
32        1.4060442272970963
36        1.4057541613525781
38        1.3867662881727878
40        1.3705053061420223
42        1.3497431114823601
44        1.3251533367939783
48        1.3111943869635805
50                         0
52        1.3394234405932892
54        1.2849157142560723
56         1.281719159327807
60        1.2600051642942829
62         1.266070385993126
64        1.2413590294280803
66        1.2298873703485311
68         1.228088614506696
72        1.2139857189070042
74        1.2173435064564189
76        1.2073445944515917
78          1.18804049227045
80         1.186304749886542
84        1.2613935471028506
88        1.2648246158850653
90        1.2466494548982199
92        1.2333924152795082
94        1.2129250072037692
96        1.1999106597943647
100       1.1902559038393383
102       1.1892563795455853
104        1.167069685125939
106       1.1615348403090369
108       1.1555563844349988
112       1.1488524666097713
114        1.143572986788779
116       1.1418015379428537
118        1.136058647502255
120       1.1236364680969286
124       1.1320498900328944
126       1.1170101762158153
128        1.120043039721982
130       1.1059773445917063
132                        0
136       1.1907902374762016
140       1.2012387088454022
142       1.1906909549024802
144       1.1764375730308343
146       1.1628110372792353
148       1.1516152840582585
152       1.1583673498348623
156       1.1692285288386206
158       1.1588148476218465
160       1.1439588147705457
162       1.1383941068159398
164                        0
168       1.2213102850395667
172       1.2031062978889062
174       1.1897147112197684
176        1.177422568842014
178        1.158443027293818
180       1.1567087516841796
184       1.0819793880779518
188        0.927952404748273
190        0.885193608411576
192       0.8581010699478283
194       0.8409352213456689
196       0.8245471942901911
200       0.7935960418803983
204       0.8183676087159205
206       0.7977644276409412
208       0.7993777411831636
210       0.7783107440628891
212       0.7803738231239117
216       0.7713058245640294
220        0.795279016979026
222       0.7824128169919247
224       0.7649414992231182
226       0.7544899426779375
228       0.7504048978314295
232       0.7407258109620256
234                        0
236       0.7308525593793626
238       0.7287255851177903
240       0.7161023377036263
244       0.7129204834988017
246       0.7141991829499618
248       0.7190570819844222
250       0.7173975428775917
252       0.7071027496463946
256        0.703531206505542
258       0.6941108278958862
260       0.6914114388869608
262       0.6971551798505504
264       0.6832460217432723
268       0.6822029317493292
272       0.7289529213213379
274       0.7139321758287004
276       0.6957731747455482
278       0.7018312962317095
280       0.6911808244378487
284       0.6843279752855028
286       0.6741394908812485
288       0.6670070174301739
290       0.6804085117374855
292       0.6617864063235485
296       0.6623168733492338
298       0.6679358357181778
300       0.6488990885270688
302       0.6503639129625527
304       0.6572077690202801
308       0.6363517458476216
310       0.6536449360948587
312       0.6391428272150887
314       0.6482206049496236
316       0.6287957471922729
320       0.6380571850193401
324       0.6554825047832906
326       0.6484934835397033
328       0.6454071687844921
330       0.6427008031845645
332       0.6352454880802477
336       0.6156760019587869
340       0.6170833682807023
342       0.6434227390858672
344       0.6278124433742752
346       0.6290078315253372
348                        0
352       0.6266355568292261
356       0.6495813516716594
358       0.6337485177966306
360       0.6298550929085645
362       0.6183063778386736
364       0.6069476168507777
368       1.6579955793677608
372       1.5076933476098775
374       1.4989223343608031
376       1.4782919502497789
378        1.461856891390611
380       1.4509592706473475
384        1.451746997147108
388        1.444392866287476
390        1.432738323965376
392        1.417241201438662
394       1.4057559944573452
396       1.3902706269897063
400       1.4196659307880326
404       1.4190563985232272
406        1.404272356704056
408       1.3916140490958342
410       1.3749618350294734
412       1.3545155713071164
416       1.3440223073315984
418                        0
420        1.372384475860572
422       1.3184105752674413
424       1.3112727599578604
428       1.2970172419001187
430       1.2995219526631718
432       1.2826154066729571
434          1.2752890152407
436       1.2735572473264072
440       1.2594114333938535
442       1.2631632585495876
444       1.2491717310136363
446        1.233984347835307
448        1.240031992028868
452         1.30370857198071
456        1.315055963470538
458       1.2888738300982074
460       1.2877137595885193
462       1.2673379985315463
464        1.250594345697306
468       1.2487131179395878
470        1.248002326082933
472       1.2300895244599586
474       1.2244197121500935
476       1.2186682845116386
480       1.2037865236033616
482       1.1947642300832226
484       1.2052091893871497
486       1.1955746593628465
488       1.1888497102149884
492       1.1915605250807406
494       1.1726587153109655
496       1.1841133872494156
498       1.1576825122317769
500                        0
504        1.259355851168598
508        1.265883375278026
510       1.2472598673184119
512        1.232808747256218
514       1.2319592783041904
516        1.220785786262778
520       1.2275441303266783
524       1.2386788414290355
526       1.2283577755407058
528       1.2095481507570451
530       1.2082142070681048
532                        0
536       1.2998734542832147
540       1.2691220651743778
542       1.2555144634690785
544       1.2519876926897657
546       1.2374982003019996
548       1.2231273969878986
552       1.7282392323598248
556       1.5161488467923143
558        1.503121190703977
560         1.48586566102824
562       1.4694562316392716
564       1.4589554592644807
568       1.4556853555098295
572        1.456232262380321
574       1.4440592236675138
576        1.428294264765868
578       1.4199848948034668
580       1.4043226018516568
584       1.4234351301615986
588       1.4339948857967295
590       1.4185177047756572
592       1.4056313337829422
594       1.3890214025155618
596       1.3723339082737365
600       1.3615778905990565
602                        0
604       1.4100282016237429
606       1.3395671374926488
608       1.3291515487117478
612       1.3181687033905718
614        1.312423708466101
616       1.2993237532162487
618       1.2877483042174591
620       1.2865282739749122
624       1.2719636386987183
626       1.2714495345417192
628       1.2615423884659074
630       1.2421201619204132
632       1.2402537441669796
636       1.2851130012242886
640       1.3043327841699193
642       1.2778639041619957
644       1.2723464591651539
646       1.2477883952768762
648       1.2352499196655526
652        1.229251291851949
654        1.223890910501634
656        1.205423323571373
658       1.1957824090008151
660       1.1900729496698461
664        1.179201763233652
666        1.169504032514554
668         1.16772376849918
670       1.1579256145829042
672       1.1499812813376982
676        1.150285902223034
678       1.1349452274085248
680       1.1380960963513609
682        1.123711172150547
684                        0
688        1.214119211354098
692        1.211944797522819
694       1.1971248679331923
696       1.1822892151870987
698       1.1645336676778397
700       1.1535559567518647
704       1.1601987101282065
708       1.1711716308206082
710       1.1563410270783216
712        1.141082456193516
714       1.1352383596118123
716                        0
720       1.2530847858282803
724       1.2050453590356518
726         1.19119860196273
728         1.17463817374538
730       1.1555432048235512
732       1.1538041170229467
738        1.713782642126885
740       1.6955681658647108
742       1.6814906372051954
744       1.6786372409532953
746       1.6694168550864992
750                        0
754       1.6506423382064332
756       1.6424273190907783
758       1.6353664801041328
762        1.633232875930849
764       1.6258840554387932
766        1.617976174654771
768       1.6136652707273988
770        1.605821026619692
774       1.6033527961961531
776       1.5951342406182645
778       1.5878135544728507
780       1.5800601969084245
782        1.575565087879128
786       1.5950169012164208
790       1.5898075522577595
792       1.5807953202097411
794       1.5704333289187615
796       1.5643368431897877
798        1.558307017802491
802       1.5537149289772467
804        1.549528250585513
806       1.5424430535161062
808         1.54256227031715
810       1.5309356452520158
814       1.5247733176952427
816       1.5196742408779502
818       1.5123696925788683
820        1.499914486202397
822       1.4924106271188253
826        1.492624987952706
828       1.4924024018806028
830       1.4853020201751674
832        1.477208127101587
834       1.4694738525181406
838     0.057034391042653794
842       0.0571536334895882
844      0.05729366005937665
846      0.05744203185278054
848      0.06713062107721124
851      0.06714781920234739
853      0.06732001211690299
855      0.06784038051613318
857      0.06799604927210635
859      0.06828011147886554
863      0.06844632943125976
865      0.06851361914788083
867      0.06887402435616684
869     0.056544389321695726
871      0.06918353164189846
875     0.059122086455436665
877      0.06956120084140223
879      0.07017897804376615
881      0.07028148183862523
883      0.05787364202878375
887      0.07056618554293374
889        0.057989410208958
891      0.07129266446800787
893      0.07146546557664281
895       0.0716254973792324
899      0.07192596356272017
903     0.058840095111364746
905      0.07213853480103966
907      0.07231835711877917
909      0.05938170626668099
911      0.07294488485625279
915      0.07306917734079586
917      0.07317054128128272
919      0.07347430293304898
921      0.06010697591831878
923      0.07383162509955737
927     0.060495215307428206
929     0.060604010237618126
931      0.06073438432235217
933      0.06099653048237791
935     0.061130459259873135
939      0.06129124410987595
941      0.06130329065804092
943     0.061151661574090986
945     0.061405387192057306
947      0.06175780765942851
951       1.5250840516518187
955        1.552568811301301
957       1.5427752626774387
959       1.5331932831264679
961       1.5152721949172019
963       1.5074989761997712
967       1.4896288908647644
969       1.4780778852088083
971       1.4700035345334466
973       1.4565623180137077
975        1.445976962830235
979       1.4325855992469252
981       1.4197344854662965
983        1.401262575071573
985       1.3862945308535968
987        1.384130256052478
993        1.361508332192898
995        1.351001663879717
997       1.3282588067265129
999       1.3257206687421472
1003      1.3142909715978441
1005      1.3003260094811093
1007      1.2881071401556836
1009      1.2767801501201566
1012      1.7048641073512139
1014      1.8940319526948572
1016      1.8747686491853095
1018      1.8654947184112376
1020      1.8527398169018068
1024       1.844174397003866
1026      1.8430238477512753
1028      1.8302818174911863
1030      1.8173838456081814
1032      1.8057992981104682
1036      1.8149829605049186
1038      1.7995150369321797
1040      1.7866516942518147
1042      1.7735550719416031
1044       1.769995333364443
1048       1.799526080374287
1050      1.7968530684449833
1052      1.7838265504081745
1054      1.7696444491040102
1056      1.7512940457049684
1060      1.7697554297961993
1062      1.7547726933914918
1064      1.7389166355812984
1066      1.7337200518764075
1068      1.7150972597500092
1072      1.7462926148815636
1074       1.719149261914565
1076       1.711582246191498
1080      1.7005124371100973
1084      1.7080989351250158
1086       1.691435430587127
1088      1.6844494328889932
1090       1.664037581688075
1092      1.6686372014231974
1096      1.6899344075625968
1098       1.669431712846442
1100      1.6634226761839213
1102      1.6436152195947373
1104      1.6358000873538245
1108     0.11903831859341765
1112      0.4729861500927512
1114     0.16280793829202067
1116      0.4787632853388766
1118      0.4711383364607152
1120      0.4668172561120673
1128      0.4627052684317185
1132      0.4412227248835694
1134     0.44354421943965844
1136      0.4126655541164234
1140      1.7461791006389626
1144      1.7695250734505363
1146      1.7715391419501945
1148       1.770625483958279
1150      1.7704040639447296
1152      1.7695081788801759
1156      1.7638356274269416
1160      1.7715725869786123
1162      1.7701196454489683
1164      1.7667569752860521
1166      1.7648743629092642
1168       1.763838685943225
1172      1.7657225752056789
1174      1.7645632809383045
1176      1.7608991948479125
1178      1.7598362095817717
1180      1.7590955400143164
1184      1.7560495443976523
1186      1.7571677199949287
1188      1.7558911269459976
1190      1.7533419072229914
1192      1.7506673845335168
1196      1.7510006664162403
1198      1.7496058853847873
1200      1.7477359172183355
1202      1.7444225468099093
1204       1.743308366083936
1208      1.6556691733888471
1212        1.64297669457593
1214      1.6343822729361266
1216      1.6265067062165601
1218       1.618865991735961
1220      1.6114968339209264
1224      1.3240805773461226
1228      1.3153386221697692
1230      0.6734628137095633
1234      0.7913062105760345
1236      0.7865824034601745
1238      0.7795871426061582
1240      0.7628241523125163
1242      0.7405021514606399
1250      0.7733165409025605
1254      0.7407399462256391
1256      0.7446218752617147
1258      0.7149875629820736
1262      1.7075144448533202
1266       1.730880859428193
1268      1.7328212845233328
1270      1.7317734323431513
1272      1.7341296392350067
1274      1.7334756929990074
1278      1.7243057179457875
1282      1.7318975861687205
1284      1.7333691208377457
1286       1.732175650153278
1288      1.7334832776102866
1290       1.732372495746513
1294      1.7338175297202416
1296      1.7329630786357868
1298      1.7318839084573339
1300      1.7306960059812662
1302      1.7296011601947467
1306      1.7296187381064656
1308      1.7307198617163877
1310       1.729274556175907
1312      1.7297962212599596
1314      1.7268942069037494
1318      1.7272191689306016
1320      1.7285674981160106
1322       1.726636381605547
1324      1.7262424141835067
1326      1.7252725927602899
1330      1.6668026877455053
1334       1.666754853762041
1336      1.6583274448761054
1338        1.65032263550715
1340      1.6493406341242296
1342       1.641919055037739
1346       0.425812451177779
1350      0.5569902643736575
1353       1.697507332205763
1355       1.844701206961174
1357      1.8254376674722927
1359       1.815750429913437
1361      1.8132993337127028
1365      1.8151647619660576
1367      1.8143317955190057
1369       1.801343601809866
1371      1.7881558802945825
1373      1.7760714604539518
1377      1.7852807447597443
1379      1.7698116401111978
1381      1.7565231680521758
1383      1.7543413277348154
1385      1.7392875506998715
1389      1.7797845109331345
1391      1.7657088508465202
1393      1.7523941408724169
1395      1.7380191225603105
1397      1.7312214443143976
1401      1.7379128985265808
1403      1.7224270683625882
1405      1.7184213765608034
1407      1.7010220930648232
1409       1.693698739563104
1413       1.713072721286705
1415      1.6976972688567131
1417      1.6899314034061208
1421       1.678389965463405
1425      1.6737947494868326
1427      1.6687898927884715
1429      1.6492566306631427
1431      1.6409676757039668
1433      1.6456360229757092
1437       1.654547743574037
1439      1.6461201520877546
1441      1.6275119188151763
1443      1.6200530533464497
1445       1.612079811711934
1452      1.8046847720100736
1454      1.8047833214525881
1456       1.797618668222458
1458      1.7929913687761174
1460      1.7919180081592216
1464       1.775026135903797
1468      1.7920487852223415
1471       1.790475801581265
1473      1.7868365091987264
1475      1.7871529619962185
1479      1.7816340617009505
1483      1.7850235136604733
1487      1.7789060856417256
1489      1.7738387518973049
1491       1.769682881523146
1495      1.7408787283206992
1499      1.7648189744011906
1501      1.7617857390844023
1503        1.75770610357021
1505      1.7519375960601256
1507      1.7521244035832177
1514      1.7597714133989641
1516      1.7483011320324189
1518      1.7411482627836237
1520      1.7363833316311177
1522       1.736559066269527
1526      1.7172335652295245
1531      1.7287126633755356
1533      1.7314706281853145
1535      1.7282350363146088
1537       1.720344742291621
1539      1.7221734367707637
1543                       0
1547      1.7036476485918646
1549      1.6958375743577971
1551      1.6949064846676911
1555      1.6874768094352455
1557       1.685989172917945
1559      1.6782864747774933
1561      1.6739647640901527
1563      1.6722378801237066
1567      1.6759897900491967
1569      1.6618247672847988
1571      1.6606710352566112
1573      1.6530644874507203
1575       1.649953986270456
1579       1.681297805444492
1583      1.6700520424481298
1585       1.667181860354792
1587      1.6568865613275168
1589      1.6449819446579936
1591       1.639214585000014
1595      1.6410599890208055
1597      1.6432696512198481
1599      1.6298673102402295
1601      1.6238536344658807
1603      1.6186308887044174
1607      1.6193418112441196
1609       1.614593271326993
1611      1.6072040891927848
1613      1.6012663590062357
1615      1.5940407410631041
1619      1.5946888289374477
1621      1.5882100957302596
1623       1.587985558077698
1625      1.5799165406650344
1627      1.5655946193652834
1631     0.07070127737340176
1635     0.08416878530139071
1637     0.08443785621465827
1639     0.08478919060590338
1641     0.09334258183442584
1644     0.10603180131397782
1646       0.106505866207118
1648     0.09439111585512952
1650     0.09450595927387112
1652     0.08211456108215626
1656     0.09518470631946747
1658     0.09539129998659052
1660     0.08289664565854568
1662     0.08343199036452603
1664     0.09624772156495698
1668      0.0871279249656989
1670     0.09681912182757578
1672     0.08440054891345107
1674     0.09770121716674529
1676     0.08517426476572666
1680     0.08471993544879124
1682     0.08548836969893649
1684     0.08577749933433501
1686     0.08595553255245832
1688     0.08614796979658328
1692     0.08652450808993331
1696     0.08676036428685732
1698     0.08662025389371077
1700      0.0869802394927499
1702     0.07387787113473963
1704     0.08775865702231889
1708     0.08790576300272998
1710     0.08808784882200178
1712     0.08834250268158712
1714     0.07463055332745072
1716     0.07485698665122698
1720     0.07527573643141765
1722     0.07532351860488727
1724     0.07553765302367196
1726     0.07584285606128259
1728      0.0759921803489148
1732     0.07621652609591999
1734     0.06216923141552526
1736      0.0759822277461493
1738     0.06227013548943564
1740     0.06259446608798445
1744      1.4377344766079456
1748      1.5246019289244055
1750      1.5215273965539478
1752      1.5155323631175952
1754      1.5044249661534554
1756      1.5001507149498807
1760       1.489011227320312
1762      1.4810149357562845
1764       1.476262027748574
1766      1.4662551025438961

In [14]:
cap_text = df["Capacity"].astype("string").str.strip()

df.loc[cap_text == "[]", "Capacity"] = pd.NA
df["Capacity"] = pd.to_numeric(df["Capacity"], errors="coerce")

In [15]:
summary = pd.DataFrame({
    "dtype": df.dtypes,
    "non_null": df.count(),
    "null": df.isnull().sum()
})

summary

                              dtype  non_null  null
type                            str      7412     0
start_time           datetime64[us]      7412     0
ambient_temperature           int64      7412     0
battery_id                      str      7412     0
test_id                       int64      7412     0
uid                           int64      7412     0
filename                        str      7412     0
Capacity                    float64      2720  4692
Re                              str      1910  5502
Rct                             str      1910  5502